# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/himlen/rgbd_seg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/himlen/rgbd_seg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/himlen/rgbd_seg/CMakeFiles /home/himlen/rgbd_seg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/himlen/rgbd_seg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named normal

# Build rule for target.
normal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 normal
.PHONY : normal

# fast build rule for target.
normal/fast:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/build
.PHONY : normal/fast

#=============================================================================
# Target rules for targets named rawpixel

# Build rule for target.
rawpixel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rawpixel
.PHONY : rawpixel

# fast build rule for target.
rawpixel/fast:
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/build
.PHONY : rawpixel/fast

#=============================================================================
# Target rules for targets named rawpixelrgbd

# Build rule for target.
rawpixelrgbd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rawpixelrgbd
.PHONY : rawpixelrgbd

# fast build rule for target.
rawpixelrgbd/fast:
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/build
.PHONY : rawpixelrgbd/fast

#=============================================================================
# Target rules for targets named superpixel

# Build rule for target.
superpixel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 superpixel
.PHONY : superpixel

# fast build rule for target.
superpixel/fast:
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/build
.PHONY : superpixel/fast

gco/GCoptimization.o: gco/GCoptimization.cpp.o
.PHONY : gco/GCoptimization.o

# target to build an object file
gco/GCoptimization.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/GCoptimization.cpp.o
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/GCoptimization.cpp.o
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/GCoptimization.cpp.o
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/GCoptimization.cpp.o
.PHONY : gco/GCoptimization.cpp.o

gco/GCoptimization.i: gco/GCoptimization.cpp.i
.PHONY : gco/GCoptimization.i

# target to preprocess a source file
gco/GCoptimization.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/GCoptimization.cpp.i
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/GCoptimization.cpp.i
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/GCoptimization.cpp.i
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/GCoptimization.cpp.i
.PHONY : gco/GCoptimization.cpp.i

gco/GCoptimization.s: gco/GCoptimization.cpp.s
.PHONY : gco/GCoptimization.s

# target to generate assembly for a file
gco/GCoptimization.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/GCoptimization.cpp.s
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/GCoptimization.cpp.s
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/GCoptimization.cpp.s
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/GCoptimization.cpp.s
.PHONY : gco/GCoptimization.cpp.s

gco/LinkedBlockList.o: gco/LinkedBlockList.cpp.o
.PHONY : gco/LinkedBlockList.o

# target to build an object file
gco/LinkedBlockList.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/LinkedBlockList.cpp.o
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/LinkedBlockList.cpp.o
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/LinkedBlockList.cpp.o
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/LinkedBlockList.cpp.o
.PHONY : gco/LinkedBlockList.cpp.o

gco/LinkedBlockList.i: gco/LinkedBlockList.cpp.i
.PHONY : gco/LinkedBlockList.i

# target to preprocess a source file
gco/LinkedBlockList.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/LinkedBlockList.cpp.i
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/LinkedBlockList.cpp.i
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/LinkedBlockList.cpp.i
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/LinkedBlockList.cpp.i
.PHONY : gco/LinkedBlockList.cpp.i

gco/LinkedBlockList.s: gco/LinkedBlockList.cpp.s
.PHONY : gco/LinkedBlockList.s

# target to generate assembly for a file
gco/LinkedBlockList.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/LinkedBlockList.cpp.s
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/LinkedBlockList.cpp.s
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/LinkedBlockList.cpp.s
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/LinkedBlockList.cpp.s
.PHONY : gco/LinkedBlockList.cpp.s

gco/graph.o: gco/graph.cpp.o
.PHONY : gco/graph.o

# target to build an object file
gco/graph.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/graph.cpp.o
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/graph.cpp.o
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/graph.cpp.o
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/graph.cpp.o
.PHONY : gco/graph.cpp.o

gco/graph.i: gco/graph.cpp.i
.PHONY : gco/graph.i

# target to preprocess a source file
gco/graph.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/graph.cpp.i
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/graph.cpp.i
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/graph.cpp.i
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/graph.cpp.i
.PHONY : gco/graph.cpp.i

gco/graph.s: gco/graph.cpp.s
.PHONY : gco/graph.s

# target to generate assembly for a file
gco/graph.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/gco/graph.cpp.s
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/gco/graph.cpp.s
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/gco/graph.cpp.s
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/gco/graph.cpp.s
.PHONY : gco/graph.cpp.s

normal.o: normal.cpp.o
.PHONY : normal.o

# target to build an object file
normal.cpp.o:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/normal.cpp.o
.PHONY : normal.cpp.o

normal.i: normal.cpp.i
.PHONY : normal.i

# target to preprocess a source file
normal.cpp.i:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/normal.cpp.i
.PHONY : normal.cpp.i

normal.s: normal.cpp.s
.PHONY : normal.s

# target to generate assembly for a file
normal.cpp.s:
	$(MAKE) -f CMakeFiles/normal.dir/build.make CMakeFiles/normal.dir/normal.cpp.s
.PHONY : normal.cpp.s

rawpixel.o: rawpixel.cpp.o
.PHONY : rawpixel.o

# target to build an object file
rawpixel.cpp.o:
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/rawpixel.cpp.o
.PHONY : rawpixel.cpp.o

rawpixel.i: rawpixel.cpp.i
.PHONY : rawpixel.i

# target to preprocess a source file
rawpixel.cpp.i:
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/rawpixel.cpp.i
.PHONY : rawpixel.cpp.i

rawpixel.s: rawpixel.cpp.s
.PHONY : rawpixel.s

# target to generate assembly for a file
rawpixel.cpp.s:
	$(MAKE) -f CMakeFiles/rawpixel.dir/build.make CMakeFiles/rawpixel.dir/rawpixel.cpp.s
.PHONY : rawpixel.cpp.s

rawpixelrgbd.o: rawpixelrgbd.cpp.o
.PHONY : rawpixelrgbd.o

# target to build an object file
rawpixelrgbd.cpp.o:
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/rawpixelrgbd.cpp.o
.PHONY : rawpixelrgbd.cpp.o

rawpixelrgbd.i: rawpixelrgbd.cpp.i
.PHONY : rawpixelrgbd.i

# target to preprocess a source file
rawpixelrgbd.cpp.i:
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/rawpixelrgbd.cpp.i
.PHONY : rawpixelrgbd.cpp.i

rawpixelrgbd.s: rawpixelrgbd.cpp.s
.PHONY : rawpixelrgbd.s

# target to generate assembly for a file
rawpixelrgbd.cpp.s:
	$(MAKE) -f CMakeFiles/rawpixelrgbd.dir/build.make CMakeFiles/rawpixelrgbd.dir/rawpixelrgbd.cpp.s
.PHONY : rawpixelrgbd.cpp.s

superpixel.o: superpixel.cpp.o
.PHONY : superpixel.o

# target to build an object file
superpixel.cpp.o:
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/superpixel.cpp.o
.PHONY : superpixel.cpp.o

superpixel.i: superpixel.cpp.i
.PHONY : superpixel.i

# target to preprocess a source file
superpixel.cpp.i:
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/superpixel.cpp.i
.PHONY : superpixel.cpp.i

superpixel.s: superpixel.cpp.s
.PHONY : superpixel.s

# target to generate assembly for a file
superpixel.cpp.s:
	$(MAKE) -f CMakeFiles/superpixel.dir/build.make CMakeFiles/superpixel.dir/superpixel.cpp.s
.PHONY : superpixel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rawpixelrgbd"
	@echo "... normal"
	@echo "... rawpixel"
	@echo "... superpixel"
	@echo "... gco/GCoptimization.o"
	@echo "... gco/GCoptimization.i"
	@echo "... gco/GCoptimization.s"
	@echo "... gco/LinkedBlockList.o"
	@echo "... gco/LinkedBlockList.i"
	@echo "... gco/LinkedBlockList.s"
	@echo "... gco/graph.o"
	@echo "... gco/graph.i"
	@echo "... gco/graph.s"
	@echo "... normal.o"
	@echo "... normal.i"
	@echo "... normal.s"
	@echo "... rawpixel.o"
	@echo "... rawpixel.i"
	@echo "... rawpixel.s"
	@echo "... rawpixelrgbd.o"
	@echo "... rawpixelrgbd.i"
	@echo "... rawpixelrgbd.s"
	@echo "... superpixel.o"
	@echo "... superpixel.i"
	@echo "... superpixel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

